-- Add color columns to settings table
-- This allows for dynamic theme customization from the admin panel.
ALTER TABLE public.settings
ADD COLUMN gradient_colors jsonb DEFAULT '{
  "home_from": "#000759",
  "home_to": "#1b005b",
  "reg_from": "#4d02b1",
  "reg_to": "#001187",
  "ticket_from": "#4d02b1",
  "ticket_to": "#001187"
}'::jsonb;

-- Create notifications table
-- This table will store notifications that can be displayed to users.
CREATE TABLE public.notifications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    description text,
    video_url text,
    is_active boolean DEFAULT true NOT NULL,
    "order" integer NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Enable RLS for notifications table
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

-- Policy: Public users can read active notifications
-- This ensures that only enabled notifications are visible to the public.
CREATE POLICY "Public can read active notifications"
ON public.notifications
FOR SELECT
USING (is_active = true);

-- Policy: Admins can manage all notifications
-- This gives full control (create, read, update, delete) over notifications to authenticated users (admins).
CREATE POLICY "Admins can manage all notifications"
ON public.notifications
FOR ALL
USING (auth.role() = 'authenticated');
